### ISSUE TITLE
Access to game's memory

### ISSUE THREAD

**Issue by Remblej** [arianrhodsandlot/nostalgist#12]
Hey, I could not manage to get access to rom's memory. 
I think retroArch provides such feature, could we get this in Nostalgist?

**Comment by arianrhodsandlot** [comment]
Unfortunately, this seems to be harder than I thought.
I tried 2 ways.
+ In Nostalgist.js, we use [these commands](https://docs.libretro.com/development/retroarch/network-control-interface/#commands) to interact with RetroArch, but there aren't any commands related with SRAM saving.
+ I also tried to set the `autosave_interval` option for RetroArch to `10`. If this can work, we can use code like this to retrieve the SRAM file.
  ```js
  const FS = nostalgist.getEmscriptenFS()
  const sram = FS.readFile('/home/web_user/retroarch/userdata/saves/FCEUmm/xxx.srm')
  ```
  But I didn't success. Maybe there are some issues with the official RetroArch build for web.

I'll keep researching to find a proper approach and any suggestions are also welcome.

**Comment by Remblej** [comment]
Thanks for quick answer.
In my attempts for a workaround I'm trying to get ram data from save state file, which I think is possible;  but I have to know the layout of this file, which can differ between emulated systems. I can't find any information about retro arch's layout for this file tho :(

**Comment by Remblej** [comment]
I wasn't able to come to succeed.
Tried to scan save state file to find memory value sequence that I would expect in SRAM, but I couldn't. Apparently it's not that easy

**Comment by arianrhodsandlot** [comment]
I just noticed that the official RetroArch Emscripten build exposed a `_cmd_savefiles` method, we can use it to export the SRAM file.

```js
const nostalgist = Nostalgist.launch(/* options */)
const Module = nostalgist.getEmscriptenModule();
const FS = nostalgist.getEmscriptenFS()

// use this to save SRAM
Module._cmd_savefiles()
// read the SRAM file as Uint8Array
FS.readFile('/home/web_user/retroarch/userdata/saves/<emulator core name>/<ROM file name>.srm')
```

Is this what you are expecting?

**Comment by Remblej** [comment]
It would be great, but it doesn't work for me
```js
var fs = n.getEmscriptenFS()
var m = n.getEmscriptenModule()
fs.readdir('/home/web_user/retroarch/userdata/saves/')
> (3) ['FCEUmm', '.', '..']
fs.readdir('/home/web_user/retroarch/userdata/saves/FCEUmm')
> (2) ['.', '..']
m._cmd_savefiles()
fs.readdir('/home/web_user/retroarch/userdata/saves/FCEUmm')
> (2) ['.', '..']
```
Have you been able to make this work?

**Comment by arianrhodsandlot** [comment]
I succeeded and here is a [demo](https://codepen.io/arianrhodsandlot/pen/GReovYM?editors=1010). Do games you tried have in-game saving feature? For reference, [here is a list of NES games with in-game saving](https://consolemods.org/wiki/NES:List_of_NES_Games_with_Save_Batteries).

**Comment by Remblej** [comment]
Alright, the in-game saving support is the culprit, thanks for the investigation.
I tried Super Mario Bros, which does not support it, it's a piety.
I'm creating a platform/app for my friends that has one challenge every day, so that we can compete. One such challenge would be to get the highest score in smb 1-1. For that I wanted to get access to memory (to check score and detect changing level or dying). I assume it's not possible then?

**Comment by arianrhodsandlot** [comment]
Oh I think I misunderstood you since you are not trying to export saving files like SRAM or emulator's save states for backup usage but to read some in-game values like scores/stages/lifes/etc.
This seems to be a very low level function and I'm afraid we can't achieve this easily at JavaScript level. The Emscripten Module returned by `nostalgist.getEmscriptenModule` exposed its memory info via something like `HEAP8`, `HEAP16`... but I have no idea how to figure out which part of the memory represent a certain in-game value.

An other practical solution might be taking a screenshot manually and extract the information you want with an OCR library like [tesseract.js](https://github.com/naptha/tesseract.js).

**Comment by Remblej** [comment]
Yep, it's hard to get stuff from HEAPx arrays. Also screenshotting freezes game for half a second. I will have to less sophisticated emulators written in js. 
Thank you for your time and answers, I think we can close this issue

**Comment by Remblej** [comment]
Hey, just FYI (and maybe for others finding this thread in the future).
I played around a little more with those HEAP arrays and I was able to find RAM in there. I'm using HEAPU8; for NES the memory starts on 2966128 dec (or 2D4270 hex), for SNES I see it's different, but it's also there.

**Comment by techsev** [comment]
Just wanted to chime in since I spent the greater part of today trying to figure this out myself. 

You can 100% access the ROM's memory using HEAPU8, and its location will be consistent each time you load the game as long as you are using the same ROM and Core. Different versions of the same game (i.e. same game but different checksum) and different cores (fceumm vs quicknes) will cause the memory locations to change without an easy way to re-locate them. For my purposes, I'm luckily able to force the CORE and require a specific ROM (Mario 3) but it does make it hard to do anything more generalist. It's too bad retroArch WASM doesn't have a better way to access the game's memory instead of ALL the momery.

**Comment by kukemc** [comment]
> I succeeded and here is a [demo](https://codepen.io/arianrhodsandlot/pen/GReovYM?editors=1010). Do games you tried have in-game saving feature? For reference, [here is a list of NES games with in-game saving](https://consolemods.org/wiki/NES:List_of_NES_Games_with_Save_Batteries)。我成功了，下面是一个[演示](https://codepen.io/arianrhodsandlot/pen/GReovYM?editors=1010)。您尝试的游戏有游戏内保存功能吗？作为参考，[以下是具有游戏内保存功能的 NES 游戏列表](https://consolemods.org/wiki/NES:List_of_NES_Games_with_Save_Batteries)。

I need a little help :( I'm working on a feature like this, retrieving a game's save file so that when I launch the game next time, I can load the save file along with it and see my previous saves in the game. This demo can export the save file, but how do I load this save file? I've been researching this feature for a whole day now. If you see this, please reply. Thank you.

**Comment by arianrhodsandlot** [comment]
@kukemc It's highly recommended to use the `saveState` and `loadState` methods instead of retrieving in-game saving files(*.srm) after calling `Module._cmd_savefiles` like the code in that demo, since in-game savings should have been included in the state file returned by `saveState`.

If you have to do so for some reasons, you might need to write the `srm` file into a specific directory in the `beforeLaunch` callback. Here's an example:

```js
Nostalgist.gba({
  rom: 'xxx.zip',
  beforeLaunch(nostalgist) {
    const FS = nostalgist.getEmscriptenFS()
    // You need to keep the base filename of the srm file and the ROM file the same.
    FS.writeFile('/home/web_user/retroarch/userdata/saves/mGBA/xxx.srm', new Uint8Array(await yourSrmFileBlob.arrayBuffer()))
  }
})
```

**Comment by kukemc** [comment]
> @kukemc It's highly recommended to use the `saveState` and `loadState` methods instead of retrieving in-game saving files(*.srm) after calling `Module._cmd_savefiles` like the code in that demo, since in-game savings should have been included in the state file returned by `saveState`.
> 
> If you have to do so for some reasons, you might need to write the `srm` file into a specific directory in the `beforeLaunch` callback. Here's an example:
> 
> ```js
> await Nostalgist.gba({
>   rom: 'xxx.zip',
>   async beforeLaunch(nostalgist) {
>     const FS = nostalgist.getEmscriptenFS()
>     // You need to keep the base filename of the srm file and the ROM file the same.
>     FS.writeFile('/home/web_user/retroarch/userdata/saves/mGBA/xxx.srm', new Uint8Array(await yourSrmFileBlob.arrayBuffer()))
>   }
> })
> ```

thanks!!
