### ISSUE TITLE
`SELECT`(rshift on keyboard) button not work in nes.

### ISSUE THREAD

**Issue by daGaiGuanYu** [arianrhodsandlot/nostalgist#15]
I tried Retroassembly, not work too.

**Comment by daGaiGuanYu** [comment]
Is it possible for you to give me some clues to the source code of keyboard event listener?
I might be able to make a little contribution.

**Comment by arianrhodsandlot** [comment]
Thanks for your willingness to contribute! However, this seems to be an upstream problem that we cannot put any effort into. 

The browser keyboard events are handled by RetroArch directly, without being modified by Nostalgist.js. I guess the reason you are encountering this issue is that you are using an [IME](https://developer.mozilla.org/en-US/docs/Glossary/Input_method_editor), and sometimes that can lead to the `event.code` being modified, while the `event.code` is used internally by RetroArch.

You can check if you are receiving the expected `event.code` at [keycode.info](https://keycode.info/).

To work around this, you can try to turn off your IME or use another key as the key mapping for the <kbd>select</kbd> button. Let's say the quote key <kbd>'</kbd> is being chosen:
```js
await Nostalgist.launch({
  core: 'fceumm',
  rom: 'your-game.nes',
  retroarchConfig: {
    input_player1_select: 'quote',
  },
})

```

**Comment by daGaiGuanYu** [comment]
Ooooh, sorry.
It works in my another laptop.

But my computor works on [keycode.info](https://keycode.info/), wield.
thanks for answering.
