### ISSUE TITLE
Failed to launch without user gesture.

### ISSUE THREAD

**Issue by daGaiGuanYu** [arianrhodsandlot/nostalgist#18]
This is a repo reproducing this question: https://github.com/daGaiGuanYu/show-me-bugs/tree/nostalgist240207

warn message in console:
```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
```

I don't know whether this can be fixed.  
If not, it would be nice to mention it in the documentation.  
Developer could show a dialog to tell users "rom download, start now?".  
And user's clicking will offer a "user gesture", and this limit are gone.  

---
I'm making [a little APP](https://github.com/OC-666/nes) (not completed):
+ load nes games from local and the internet.
+ Installable, and offline playing(not completed), and launching by clicking a nes file.

---

<img width="1060" alt="截屏2024-02-07 15 55 07" src="https://github.com/arianrhodsandlot/nostalgist/assets/27003009/d01a79eb-645d-450c-ab8c-811f0364115b">

---

<img width="1029" alt="截屏2024-02-07 15 54 19" src="https://github.com/arianrhodsandlot/nostalgist/assets/27003009/d7ac7491-712a-4c2b-82e9-2d0a912670e6">

**Comment by daGaiGuanYu** [comment]
Make a user gesture before launch:
``` js
// ...
await make_usergesture()
Nostalgist.launch(...)

function make_usergesture () {
  const div = document.createElement('div')
  div.style.position = 'fixed'
  div.style.left = '0'
  div.style.top = '0'
  div.style.right = '0'
  div.style.bottom = '0'
  div.style.zIndex = '1000'

  div.style.background = '#333'
  div.style.color = '#fff'
  div.style.display = 'grid'
  div.style.placeItems = 'center'

  div.innerHTML = 'Please click on the screen to continue'

  return new Promise<void>(res => {
    div.addEventListener('click', () => {
      document.body.removeChild(div)
      res()
    })
    document.body.appendChild(div)
  })
}
```

**Comment by arianrhodsandlot** [comment]
It's a limitation from the browser (see https://developer.chrome.com/blog/autoplay) so we cannot bypass it. We have to ensure the `launch` method is invoked after a user click event or a keyboard event.

In fact, there is an undocumented parameter `waitForInteraction` working like this:
```js
await Nostalgist.nes({
  rom: 'flappybird.nes',
  waitForInteraction({ done }) {
    const button = document.createElement('button')
    button.textContent = 'click to start'
    document.body.append(button)
    button.addEventListener('click', () => {
      done()
      button.remove()
    })
  },
})
```
It still haven't been added to the documentation now, since it's a bit complex to explain, and I also think the API design may have room to improve to achieve better clarity.
I think your approach for making a user gesture before launching is quite straightforward and you could just keep using it.
