### ISSUE TITLE
Error when trying to load ROMs from external CORS-enabled server 

### ISSUE THREAD

**Issue by gitGalu** [arianrhodsandlot/nostalgist#23]
Hi!
I think that there’s a bug that causes all rom imports from external CORS-enabled domains to fail. It's easy to reproduce this with Archive.org URLs - the Internet Archive allows cross-origin downloads (and they work fine when using EmulatorJS). 
I think I can post a public domain / demoscene prod link (Game Boy) for reference :)

either
    rom: 'https://archive.org/download/pouet_54175/oh.gb',
or
    rom: 'https://archive.org/download/pouet_54175/oh.zip/oh.gb',
(plain http URLs can also be used on archive org)

**Comment by arianrhodsandlot** [comment]
Good catch!
The cause seems to be the `fetch` method called internally does not contain the parameter [`{ redirect: 'follow' }`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#follow) . 
https://github.com/arianrhodsandlot/nostalgist/blob/bb36a09bb0297c24cda40ed6dfa3e1079a6eb84f/src/nostalgist.ts#L668

A temporary workaround can be like this:
```js
const romUrl = 'https://archive.org/download/pouet_54175/oh.zip/oh.gb'
const response = await fetch(romUrl, { redirect: 'follow' })
const rom = await response.blob()
await Nostalgist.gb({ rom })
```

I'm going to fix this when I have time. But if you would like to help, feel free to raise a pull request :)

---

Additionally, I still failed to load this URL `'https://archive.org/download/pouet_54175/oh.gb'` with my workaround. As you mentioned it works fine with EmulatorJS, could you provide a simple live example, maybe with CodePen or StackBlitz? Thanks a lot!

**Comment by gitGalu** [comment]
Thanks, I'll take a look and create a PR if it helps!

It seems that only the second Archive org URL provides CORS headers (the /oh.zip one, not the /oh.gb) - my fault, only tested the first one in EmulatorJS:

Access to fetch at 'https://archive.org/download/pouet_54175/oh.gb' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

By the way, does Nostalgist support passing a .zip blob as a rom parameter or should I handle this scenario myself? A relative .zip filename works, local http URL pointing to .zip also works but not the blob (but probably unpacking a zip and passing an unpacked file blob will work).

**Comment by gitGalu** [comment]
OK, a small update. The redirect: follow fix seems unnecessary as I can confirm that this example works fine with most recent Nostalgist build w/o any changes:

      const { Nostalgist } = await import('https://esm.run/nostalgist');
      nostalgist = await Nostalgist.launch({
          rom: 'https://archive.org/download/pouet_54175/oh.zip/oh.gb',
          core: 'gambatte'
      });

But there's a problem with this URL (It may sound stupid as it's not a valid GB ROM but some other platform disk image, but it looks like the problem is not related to emulation itself but specifically to the way the file is being fetched) :)  

      const { Nostalgist } = await import('https://esm.run/nostalgist');
      nostalgist = await Nostalgist.launch({
          rom: 'https://archive.org/download/Atari_8_bit_TOSEC_2012_04_23/Atari_8_bit_TOSEC_2012_04_23.zip/Atari%208%20bit%20%5BTOSEC%5D%2FAtari%208bit%20-%20Demos%20-%20%5BATR%5D%20%28TOSEC-v2010-08-15_CM%29%2FBitter%20Reality%20%281994-06-04%29%28Slight%29%28pl%29.zip',
          core: 'gambatte'
      });

Error importing Nostalgist:
message: "FS error"

**Comment by arianrhodsandlot** [comment]
> The redirect: follow fix seems unnecessary

That's right...  I just noticed that the `follow` is just the default value for the built in `fetch` method.

> But there's a problem with this URL

The reason seems to be the file name extraction inside Nostalgist.js is a little buggy. We are using this function to extract the file name from the link for writing the file to the file system
https://github.com/arianrhodsandlot/nostalgist/blob/bb36a09bb0297c24cda40ed6dfa3e1079a6eb84f/src/nostalgist.ts#L17-L21
And the result of the extraction of that buggy link is `'Atari 8 bit [TOSEC]/Atari 8bit - Demos - [ATR] (TOSEC-v2010-08-15_CM)/Bitter Reality (1994-06-04)(Slight)(pl).zip'`, which contains '/' while that's an invalid character as a file name.

A workaround for this problem can be setting the file name manually.
```js
const romUrl = 'https://archive.org/download/Atari_8_bit_TOSEC_2012_04_23/Atari_8_bit_TOSEC_2012_04_23.zip/Atari%208%20bit%20%5BTOSEC%5D%2FAtari%208bit%20-%20Demos%20-%20%5BATR%5D%20%28TOSEC-v2010-08-15_CM%29%2FBitter%20Reality%20%281994-06-04%29%28Slight%29%28pl%29.zip'
const response = await fetch(romUrl)
const blob = await response.blob()
await Nostalgist.launch({
    rom: {
      fileName: 'Bitter Reality (1994-06-04)(Slight)(pl).zip',
      fileContent: blob
    },
    core: 'gambatte'
});
```

And to thoroughly solve this problem, it is still necessary to improve the `baseName` function in the future.

**Comment by gitGalu** [comment]
I can confirm that it works so it appears that this issue should be closed as it was just my fault to not use the { fileName: string; fileContent: Blob } parameter with correct filename (that’s already described here: https://nostalgist.js.org/apis/launch/#rom ). Thanks!
